### ISSUE TITLE
unexpected keyword argument 'ssl_verify'

### ISSUE THREAD

**Issue by etoosamoe** [routetonull/netbox_rich_report#1]
При запуске скрипта с указанными в ридми параметрами вылезает ошибка.

```
Traceback (most recent call last):
  File "netbox_rich_report.py", line 92, in <module>
    main()
  File "netbox_rich_report.py", line 85, in main
    nb = pynetbox.api(url=netboxurl, token=token, ssl_verify=False)
TypeError: __init__() got an unexpected keyword argument 'ssl_verify'
```

Убрал в коде `ssl_verify=False` - запустился, работает.
`pynetbox (5.0.5)`

**Comment by routetonull** [comment]
Fixed using requests.Session() as described in pynetbox documentation [link](https://pynetbox.readthedocs.io/en/latest/advanced.html)
